### PR TITLE
Added topics to open data card

### PR DESCRIPTION
**Pull request by giorgichi**

### CODE REVIEW

**Comment by AmeliaMN** [comment]
This looks pretty good to me! Can you change the title of this PR so it's more descriptive? E.g., "added topics to open data card"

**Comment by jennybc** [comment]
Another one where other PRs I've just merged mean that this one has a conflict. I assume you folks are having a group discussion around this. I've given some options in #42.

**Comment by AmeliaMN** [comment]
Yep @jennybc, we're talking about this IRL. 

@giorgichi, this conflict isn't your fault (it's because multiple people were editing the same file), but because your PR is being merged later, it cropped up. If you're looking at this conversation on GitHub you should be able to resolve the conflict right here, and I'm happy to talk through it with you in person later today if you'd like! Let me know.

**Comment by giorgichi** [comment]
@AmeliaMN, thanks for the help. I have resolved the conflict.

**Comment by jennybc** [comment]
Thanks!

**Pull request merged**
