### PR TITLE
Make default data consistent with Readme

### PR DESCRIPTION
**Pull request by lmitchell4**
Make "football" the default topic, as stated in the SuperBowl example in the Readme. Right now, "open-data" is the default topic.

### CODE REVIEW

**Comment by jennybc** [comment]
Thanks! I would rather fix this the other way 'round. Open data is probably a better default. Will you change the docs to reflect that?

**Comment by lmitchell4** [comment]
Good idea! I changed the default topic in bingo() back to "open-data", updated the SuperBowl example to call "football", and made a note in the Open Data example about how this is the default topic.

**Comment by jennybc** [comment]
Thanks! Note that `README.md` is generated programmatically from `README.Rmd`. So the PR needs to either touch both file (ideal / easiest for me) or just `README.Rmd` (then I need to pull and re-render).

**Comment by lmitchell4** [comment]
Thanks for pointing out the Rmd file. I updated `README.Rmd` and then re-rendered `README.md` and committed them both. I think I've done this correctly.

**Comment by jennybc** [comment]
Thanks!

**Pull request merged**
