### PR TITLE
add test for topic length check: greather than 24

### PR DESCRIPTION
**Pull request by amysheep**
@jennybc 

One of the topic has < 24 entries currently. Let me know if you want to relax this requirement to a smaller number.

### CODE REVIEW

**Comment by jennybc** [comment]
This is a good direction to pursue! I reworked this using a custom expectation. Why? Because this way we will see the **name** of the topic that violates the exception.

Original version:

```
==> devtools::test()

Loading bingo
Testing bingo
✔ | OK F W S | Context
✖ |  1 1     | bingo
─────────────────────────────────────────────────────────
test-package.R:19: failure: each topic contains 24+ unique values
topic_len_gte24() isn't true.
Submitted topic has <=24 entries
─────────────────────────────────────────────────────────

══ Results ══════════════════════════════════════════════
OK:       1
Failed:   1
Warnings: 0
Skipped:  0
```

Updated version:

```
==> devtools::test()

Loading bingo
Testing bingo
✔ | OK F W S | Context
✖ | 12 1     | bingo
─────────────────────────────────────────────────────────
test-package.R:19: failure: each topic contains at least 24 unique values
'manuscript-review' has length 21
─────────────────────────────────────────────────────────

══ Results ══════════════════════════════════════════════
OK:       12
Failed:   1
Warnings: 0
Skipped:  0
```

Notice we also get 1 test/expectation per topic this way.

**Comment by jennybc** [comment]
Is there anything about this you want to discuss? Otherwise, let's merge because this is definitely progress.

**Comment by jennybc** [comment]
Another point about the second version is that the scope of any custom objects or expectations is very intentional. See how the test is self-contained? In general, that's a good idea. Of course, if something is used more than once, then you hoist it out and put it in a more suitable place, depending on the necessary scope, i.e. the top of the test file or even in `helper.R` or `setup.R`.

**Comment by amysheep** [comment]
Looks good! Let's merge it.

**Comment by amysheep** [comment]
Are you okay with granting me write access to this repo?

**Comment by jennybc** [comment]
> Are you okay with granting me write access to this repo?

That's definitely the plan! I'd like to wait until we've accumulated a bit more experience together and the package has the infrastructure in place for all of us to tell if PRs keep things "green".

**Pull request merged**
