### PR TITLE
proposed squares for stat-ecology and conference-calls.

### PR DESCRIPTION
**Pull request by benjamincrary**

### CODE REVIEW

**Comment by AmeliaMN** [comment]
LGTM, but I wonder if there will be merge conflicts after #43 is merged.

**Comment by jennybc** [comment]
Yep, merge conflicts. See #42 for a review of ways we can proceed.

**Comment by AmeliaMN** [comment]
Hey @benjamincrary, this conflict isn't your fault (it's because multiple people were editing the same file), but because your PR is being merged later, it cropped up. If you're looking at this conversation on GitHub you should be able to resolve the conflict right here, and I'm happy to talk through it with you in person later today if you'd like! Let me know.

**Comment by jennybc** [comment]
Thanks!

**Comment by benjamincrary** [comment]
No problem. Thanks for handling all the requests yesterday!

**Pull request merged**
