### PR TITLE
Added bad data problems

### PR DESCRIPTION
**Pull request by charlesminshew**
Adding items to bad data & open data topics.

### CODE REVIEW

**Comment by AmeliaMN** [comment]
LGTM, but I wonder if #36 gets merged first if there will be a merge conflict?

**Comment by jennybc** [comment]
> LGTM, but I wonder if #36 gets merged first if there will be a merge conflict?

Yep. See #42 for our options.

**Comment by AmeliaMN** [comment]
Hey @charlesminshew, this conflict isn't your fault (it's because multiple people were editing the same file), but because your PR is being merged later, it cropped up. If you're looking at this conversation on GitHub you should be able to resolve the conflict right here, and I'm happy to talk through the process with you in person later today if you'd like! Let me know.

**Comment by jennybc** [comment]
Thanks!

**Pull request merged**
